services:
  app:
    build: .
    container_name: incident-01
    # Проброс порта настроен ПРАВИЛЬНО (8080 хоста -> 8080 контейнера).
    # Проблема не здесь, а в том, что приложение внутри слушает 127.0.0.1.
    ports:
      - "8080:8080"
